apiVersion: batch/v1
kind: Job
metadata:
  name: idx
  namespace: kubebook-ch12-ex
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: box
          image: busybox:1.37
          command: ["sh", "-c", "echo index $JOB_COMPLETION_INDEX"]
