apiVersion: batch/v1
kind: Job
metadata:
  name: slow
  namespace: kubebook-ch12-ex
spec:
  activeDeadlineSeconds: 5
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: box
          image: busybox:1.37
          command: ["sleep", "60"]
