apiVersion: batch/v1
kind: Job
metadata:
  name: kubebook-ch12-rules
spec:
  backoffLimit: 1
  podFailurePolicy:
    rules:
      - action: FailJob
        onExitCodes:
          containerName: box
          operator: In
          values: [42]
      - action: Ignore
        onPodConditions:
          - type: DisruptionTarget
      - action: Count
        onExitCodes:
          containerName: box
          operator: In
          values: [1]
  template:
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 10
      containers:
        - name: box
          image: busybox:1.37
          command: ["sh", "-c", "echo \"exit with $EXIT_CODE\"; sleep $NAP; exit $EXIT_CODE"]
          env:
            - name: EXIT_CODE
              value: "@CODE@"
            - name: NAP
              value: "@NAP@"
