apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch14-aff
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubebook-ch14-size
                operator: In
                values: [large, medium]
              - key: kubebook-ch14-disk
                operator: Exists
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubebook-ch14-size
                operator: In
                values: [large]
  containers:
    - name: web
      image: nginx:1.28-alpine
