apiVersion: v1
kind: Pod
metadata:
  name: guest
  namespace: kubebook-ch14-ex
spec:
  tolerations:
    - key: kubebook-ch14-maint
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: kubebook-ch14-worker2
  containers:
    - name: web
      image: nginx:1.28-alpine
