apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch14-none
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubebook-ch14-size
                operator: In
                values: [xl]
  containers:
    - name: web
      image: nginx:1.28-alpine
