apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch14-pref
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubebook-ch14-size
                operator: In
                values: [large, medium, small]
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubebook-ch14-size
                operator: In
                values: [small]
  containers:
    - name: web
      image: nginx:1.28-alpine
