apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch14-tol
spec:
  tolerations:
    - key: kubebook-ch14-app
      operator: Equal
      value: blue
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: kubebook-ch14-worker3
  containers:
    - name: web
      image: nginx:1.28-alpine
