apiVersion: v1
kind: Pod
metadata:
  name: kernel
spec:
  nodeName: kubebook-ch29-worker
  securityContext:
    sysctls:
      - name: net.ipv4.tcp_keepalive_time
        value: "600"
  containers:
    - name: main
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: scratch
          mountPath: /scratch
  volumes:
    - name: scratch
      emptyDir:
        medium: Memory
