kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        kubeReserved:
          cpu: 500m
          memory: 256Mi
        systemReserved:
          cpu: 250m
          memory: 128Mi
        evictionHard:
          memory.available: 100Mi
          nodefs.available: "0%"
          imagefs.available: "0%"
          nodefs.inodesFree: "0%"
        memorySwap:
          swapBehavior: LimitedSwap
