kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        cpuManagerPolicy: static
        reservedSystemCPUs: "0"
        memoryManagerPolicy: Static
        evictionHard:
          memory.available: 100Mi
          nodefs.available: "0%"
          imagefs.available: "0%"
          nodefs.inodesFree: "0%"
        reservedMemory:
          - numaNode: 0
            limits:
              memory: 100Mi
        topologyManagerPolicy: single-numa-node
