apiVersion: v1
kind: Pod
metadata:
  name: too-big
spec:
  nodeName: kubebook-ch29-cpu-control-plane
  containers:
    - name: main
      image: busybox:1.37
      command: ["sleep", "3600"]
      resources:
        limits:
          cpu: "64"
          memory: 64Mi
