apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebook-greetings-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: [kubebook.example.com]
    resources: [greetings]
    verbs: [get, list, watch]
