apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebook-role-grantor
rules:
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [rolebindings]
    verbs: [create]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [clusterroles]
    verbs: [bind]
    resourceNames: [view]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebook-role-grantor
  namespace: kubebook-ch37-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubebook-role-grantor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: granter
