apiVersion: v1
kind: Pod
metadata:
  name: lister-nodes
  namespace: kubebook-ch37-dev
spec:
  serviceAccountName: lister
  restartPolicy: Never
  containers:
    - name: kubectl
      image: registry.k8s.io/kubectl:v1.36.4
      command: ["kubectl", "get", "nodes"]
