apiVersion: v1
kind: Pod
metadata:
  name: uses-secret
  namespace: kubebook-ch37-dev
spec:
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      envFrom:
        - secretRef:
            name: kubebook-used
