apiVersion: v1
kind: Pod
metadata:
  name: kubebook-bad
spec:
  hostNetwork: true
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
