apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch06-thr
spec:
  containers:
    - name: web
      image: nginx:1.28-alpine
      livenessProbe:
        httpGet:
          path: /
          port: 80
        successThreshold: 2
