apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
data:
  chart: {{ .Chart.Name | quote }}
  message: {{ .Values.message | quote }}
  replicas: {{ .Values.replicaCount | quote }}
  globalEnv: {{ .Values.global.env | default "none" | quote }}
  seesParentKey: {{ .Values.parentOnly | default "no" | quote }}
