apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch31-ex-a
spec:
  nodeName: kubebook-ch31-ex-control-plane
  tolerations:
    - operator: Exists
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch31-ex-b
spec:
  nodeName: kubebook-ch31-ex-worker
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
