apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: old
spec:
  template:
    metadata:
      labels: {app: old}
    spec:
      containers: [{name: c, image: registry.k8s.io/pause:3.10}]
