apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greeting-controller
rules:
  - apiGroups: [kubebook.example.com]
    resources: [greetings]
    verbs: [get, list, watch]
  - apiGroups: [kubebook.example.com]
    resources: [greetings/status]
    verbs: [patch, update]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greeting-controller
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: greeting-controller}
subjects: [{kind: ServiceAccount, name: greeting-controller}]
