apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
transformers:
  - |-
    apiVersion: builtin
    kind: PrefixTransformer
    metadata:
      name: myFancyNamePrefixer
    prefix: bob-
    fieldSpecs:
      - path: metadata/name
