apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-dongle1
spec:
  containers:
    - name: main
      image: busybox:1.37
      command: ["sleep", "3600"]
      resources:
        requests:
          example.com/dongle: "3"
        limits:
          example.com/dongle: "3"
