apiVersion: v1
kind: Pod
metadata:
  name: bad
  namespace: kubebook-ch13-ex
spec:
  containers:
    - name: web
      image: nginx:1.28-alpine
      resources:
        requests:
          cpu: 500m
        limits:
          cpu: 250m
