apiVersion: v1
kind: Pod
metadata:
  name: budget
  namespace: kubebook-ch13-ex
spec:
  terminationGracePeriodSeconds: 1
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 64Mi
  containers:
    - name: main
      image: busybox:1.37
      command: ["sleep", "3600"]
