apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-ev-late
spec:
  nodeName: kubebook-ch13-evict-control-plane
  containers:
    - name: main
      image: busybox:1.37
      command: ["sleep", "3600"]
