apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-hog
spec:
  restartPolicy: Never
  containers:
    - name: hog
      image: busybox:1.37
      command: ["sh", "-c", "echo 'eating memory'; head -c 200m /dev/zero | tail > /dev/null; echo 'done'"]
      resources:
        limits:
          memory: 50Mi
