apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebook-ch13-php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: registry.k8s.io/hpa-example
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: kubebook-ch13-php
spec:
  selector:
    app: php
  ports:
    - port: 80
