apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-podguar
spec:
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 64Mi
  containers:
    - name: one
      image: busybox:1.37
      command: ["sleep", "3600"]
    - name: two
      image: busybox:1.37
      command: ["sleep", "3600"]
