apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-podlevel
spec:
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 400m
      memory: 128Mi
  containers:
    - name: main
      image: busybox:1.37
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
    - name: side
      image: busybox:1.37
      command: ["sleep", "3600"]
