apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubebook-ch13-quota
  namespace: kubebook-ch13-q
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "3"
    configmaps: "5"
