apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-resize
spec:
  containers:
    - name: spin
      image: busybox:1.37
      command: ["sh", "-c", "while :; do :; done"]
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: RestartContainer
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
