apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch13-spin
spec:
  containers:
    - name: spin
      image: busybox:1.37
      command: ["sh", "-c", "while :; do :; done"]
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
