apiVersion: v1
kind: LimitRange
metadata:
  name: kubebook-ch13-storage
  namespace: kubebook-ch13-st
spec:
  limits:
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubebook-ch13-storage
  namespace: kubebook-ch13-st
spec:
  hard:
    persistentvolumeclaims: "2"
    requests.storage: 3Gi
