apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kubebook-ch13-php
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubebook-ch13-php
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 50m
          memory: 32Mi
        maxAllowed:
          cpu: "1"
          memory: 256Mi
