apiVersion: v1
kind: Pod
metadata:
  name: sock
  namespace: kubebook-ch39-bypass
spec:
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: sock
          mountPath: /run/containerd/containerd.sock
  volumes:
    - name: sock
      hostPath:
        path: /run/containerd/containerd.sock
