apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kubebook-ch46
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: kubebook-ch46-alb
spec:
  scheme: internet-facing
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kubebook-ch46-alb
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: kubebook-ch46-alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: kubebook-ch46
spec:
  ingressClassName: kubebook-ch46-alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
