apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-bmo
spec:
  volumes:
    - name: cache
      emptyDir: {}
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: cache
          mountPath: /cache
          bindMountOptions: [noexec]
