apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-eph
spec:
  containers:
    - name: app
      image: busybox:1.37
      command: ["sh", "-c", "dd if=/dev/zero of=/tmp/big bs=1M count=30; sleep 3600"]
      resources:
        limits:
          ephemeral-storage: 10Mi
