apiVersion: v1
kind: Pod
metadata:
  name: filler
  namespace: kubebook-ch15-ex
spec:
  volumes:
    - name: scratch
      emptyDir:
        sizeLimit: 5Mi
  containers:
    - name: app
      image: busybox:1.37
      command: ["sh", "-c", "dd if=/dev/zero of=/scratch/big bs=1M count=20; sleep 3600"]
      volumeMounts:
        - name: scratch
          mountPath: /scratch
