apiVersion: v1
kind: Pod
metadata:
  name: keeper
  namespace: kubebook-ch15-ex
spec:
  nodeName: kubebook-ch15-worker
  volumes:
    - name: keep
      hostPath:
        path: /kubebook-ch15/ex
        type: DirectoryOrCreate
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: keep
          mountPath: /keep
