apiVersion: v1
kind: Pod
metadata:
  name: twin
  namespace: kubebook-ch15-ex
spec:
  volumes:
    - name: box
      emptyDir: {}
  containers:
    - name: maker
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: box
          mountPath: /out
    - name: taker
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: box
          mountPath: /in
          readOnly: true
