apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-geph
spec:
  volumes:
    - name: scratch
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Mi
  containers:
    - name: app
      image: busybox:1.37
      command: ["sh", "-c", "echo scratch > /scratch/f; sleep 3600"]
      volumeMounts:
        - name: scratch
          mountPath: /scratch
