apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-hp
spec:
  nodeName: kubebook-ch15-worker
  volumes:
    - name: data
      hostPath:
        path: /kubebook-ch15/data
        type: Directory
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /data
