apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-hpfile
spec:
  nodeName: kubebook-ch15-worker
  volumes:
    - name: flagfile
      hostPath:
        path: /kubebook-ch15/data/flag.txt
        type: FileOrCreate
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: flagfile
          mountPath: /etc/flag.txt
