apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-mem
spec:
  volumes:
    - name: cache
      emptyDir:
        medium: Memory
        sizeLimit: 10Mi
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: cache
          mountPath: /cache
