apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-mode
spec:
  volumes:
    - name: cache
      emptyDir:
        mode: 01777
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: cache
          mountPath: /cache
