apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-root
spec:
  nodeName: kubebook-ch15-worker
  volumes:
    - name: host
      hostPath:
        path: /
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: host
          mountPath: /host
          readOnly: true
          recursiveReadOnly: Enabled
