apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-satok
spec:
  serviceAccountName: kubebook-ch15-sa
  volumes:
    - name: sa
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
  containers:
    - name: app
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: sa
          mountPath: /sa
          readOnly: true
