apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch15-two
spec:
  volumes:
    - name: box
      emptyDir: {}
  containers:
    - name: plain
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: box
          mountPath: /one
    - name: hider
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: box
          mountPath: /etc
