apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch05-ex-host
spec:
  restartPolicy: Never
  containers:
    - name: s
      image: busybox:1.37
      command: ["sh", "-c"]
      args: ["hostname"]
