apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch05-two
spec:
  containers:
    - name: web
      image: nginx:1.28-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared
          mountPath: /usr/share/nginx/html
    - name: writer
      image: busybox:1.37
      command: ["sh", "-c", "i=0; while true; do i=$((i+1)); echo \"hello $i from writer\" > /work/index.html; sleep 2; done"]
      volumeMounts:
        - name: shared
          mountPath: /work
  volumes:
    - name: shared
      emptyDir: {}
