apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: kubebook-verify-k8s-images
spec:
  validationActions: [Deny]
  webhookConfiguration:
    timeoutSeconds: 30
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kubebook-ch41-kyv
  matchImageReferences:
    - glob: "registry.k8s.io/*"
  attestors:
    - name: krel
      cosign:
        keyless:
          identities:
            - subject: krel-trust@k8s-releng-prod.iam.gserviceaccount.com
              issuer: https://accounts.google.com
  validations:
    - expression: "images.containers.map(image, verifyImageSignatures(image, [attestors.krel])).all(e, e > 0)"
      message: "The image is not signed by the Kubernetes release identity."
