apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch17-client
  labels:
    app: kubebook-ch17-client
spec:
  nodeSelector:
    kubernetes.io/hostname: kubebook-ch17-worker
  terminationGracePeriodSeconds: 1
  containers:
    - name: client
      image: busybox:1.37
      command: ["sleep", "3600"]
