apiVersion: v1
kind: Service
metadata:
  name: site-dns
  namespace: kubebook-ch17-ex
spec:
  selector:
    app: site
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
