apiVersion: v1
kind: Pod
metadata:
  name: gate
  namespace: kubebook-ch17-ex
  labels:
    app: site
spec:
  containers:
    - name: gate
      image: nginx:1.28-alpine
      ports:
        - name: http
          containerPort: 80
      readinessProbe:
        exec:
          command: ["cat", "/tmp/go"]
        periodSeconds: 2
