apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch08-cmenv
spec:
  containers:
    - name: box
      image: busybox:1.37
      command: ["sleep", "3600"]
      env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: kubebook-ch08-cm
              key: APP_COLOR
      envFrom:
        - configMapRef:
            name: kubebook-ch08-lit
        - prefix: CFG_
          configMapRef:
            name: kubebook-ch08-envfile
        - configMapRef:
            name: kubebook-ch08-cm
