apiVersion: v1
kind: Pod
metadata:
  name: reader3
  namespace: kubebook-ch08-ex
spec:
  containers:
    - name: box
      image: busybox:1.37
      command: ["sleep", "3600"]
      env:
        - name: PASS_ENV
          valueFrom:
            secretKeyRef:
              name: ex-pw
              key: pass
