apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopweb
  namespace: kubebook-ch08-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopweb
  template:
    metadata:
      labels:
        app: shopweb
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: app
          image: busybox:1.37
          command: ["sleep", "3600"]
          envFrom:
            - configMapRef:
                name: shop-cfg
