apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubebook-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubebook-ca
  namespace: kubebook-ch44-cert-manager
spec:
  isCA: true
  commonName: kubebook-ca
  secretName: kubebook-ca
  duration: 8760h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: kubebook-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubebook-ca
spec:
  ca:
    secretName: kubebook-ca
