apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch16-csiuser-N
spec:
  nodeSelector:
    kubernetes.io/hostname: kubebook-ch16-worker
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: kubebook-ch16-csi-N
  containers:
    - name: app
      image: busybox:1.37
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
