apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebook-ch16-claim-local
spec:
  storageClassName: kubebook-ch16-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
