apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebook-ch16-fake
spec:
  storageClassName: kubebook-ch16-fake
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
