apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebook-ch16-claim-a
spec:
  storageClassName: kubebook-ch16-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
