apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebook-ch16-ex-move
  namespace: kubebook-ch16-ex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
