apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebook-ch16-growclaim
spec:
  storageClassName: kubebook-ch16-grow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
