apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubebook-ch16-disk
spec:
  storageClassName: kubebook-ch16-local
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /kubebook-ch16/disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["kubebook-ch16-worker2"]
