apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebook-ch16-shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebook-ch16-writer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      terminationGracePeriodSeconds: 1
      nodeSelector:
        kubernetes.io/hostname: kubebook-ch16-worker
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kubebook-ch16-shared
      containers:
        - name: app
          image: busybox:1.37
          command: ["sh", "-c", "echo one writer >> /data/log.txt; sleep 3600"]
          volumeMounts:
            - name: data
              mountPath: /data
