apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch16-userlocal
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: kubebook-ch16-claim-local
  containers:
    - name: app
      image: busybox:1.37
      command: ["sh", "-c", "echo written by $HOSTNAME >> /data/notes.txt; sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
