apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
vars:
  - name: STYLE_VAR
    objref:
      kind: ConfigMap
      name: web-config
      apiVersion: v1
    fieldref:
      fieldpath: data.STYLE
