apiVersion: v1
kind: Pod
metadata:
  name: kubebook-ch30-oh-self
spec:
  runtimeClassName: kubebook-ch30-heavy
  overhead:
    cpu: 10m
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
