apiVersion: v1
kind: Pod
metadata:
  name: no-chmod
spec:
  terminationGracePeriodSeconds: 1
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/kubebook-no-chmod.json
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
