apiVersion: v1
kind: Pod
metadata:
  name: sandboxed-seccomp
spec:
  runtimeClassName: gvisor
  terminationGracePeriodSeconds: 1
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/kubebook-no-mkdir.json
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
