apiVersion: v1
kind: Pod
metadata:
  name: userns-hostpath
spec:
  hostUsers: false
  terminationGracePeriodSeconds: 1
  volumes:
    - name: h
      hostPath:
        path: /var/kubebook-ch40-host
        type: Directory
  containers:
    - name: c
      image: busybox:1.37
      command: ["sleep", "3600"]
      volumeMounts:
        - name: h
          mountPath: /host
