apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubebook-ch07-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs-demo
  template:
    metadata:
      labels:
        app: rs-demo-typo
    spec:
      containers:
        - name: web
          image: nginx:1.28-alpine
