apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubebook-ch09-rs
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.28-alpine
