apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubebook-ch09-rs
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.28-alpine
