apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: kubebook-ch27-prod
namePrefix: prod-
labels:
  - pairs:
      env: prod
replicas:
  - name: web
    count: 3
images:
  - name: nginx
    newTag: 1.28-alpine
patches:
  - path: limits.yaml
