apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: kubebook-ch47
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: __ACR__.azurecr.io/web:1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
